[package]
name = "core3d"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.24.2", features = ["serde", "bytemuck"] }
rmp-serde = "1.3.0"
serde = { version = "1.0.215", features = ["derive"] }
