[[language]]
name = "rust"
auto-format = true

[language-servers]
command = "rustup"
args = ["run", "nightly", "rust-analyzer"]

[language-server.rust-analyzer.config]
check.overrideCommand = [ "cargo", "3ds", "check", "--message-format=json-diagnostic-rendered-ansi" ]
cargo.target = "armv6k-nintendo-3ds"
server.extraEnv = { "DEVKITPRO" = "/opt/devkitpro", "DEVKITARM" = "/opt/devkitpro/devkitARM" }

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "0431a2c60828731f27491ee9fdefe25e250ce9c9" }


[[language]]
name = "c"
language-servers = [ "clangd" ]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

